### ISSUE TITLE
SPIKE .mpy installer doesn't correctly load a new version

### ISSUE THREAD

**Issue by ste7anste7an** [antonvh/LMS-uart-esp#6]
When using:

```
from projects.uartremote import *
ur=UartRemote("A")
print(ur.decode(ur.encode('cmd','repr',b'1234'))) 
```

gives:
```('cmd',b'repl')```
as a result.

When including the whole uartremote.py code in the SPIKE project, it works fine.

**Comment by antonvh** [comment]
How did you install the lib? Copy-paste? 
Sometimes the .mpy install doesn't update correctly.
